# This workflow runs automatically and updates the README.md file with the
# latest track on Last.fm.
name: Update Track

on:
  workflow_dispatch:
  # schedule:
  # - cron: "0 */6 * * *"

jobs:
  get-track:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Update corepack
        run: npm i -g corepack@latest

      - name: Enable corepack
        run: corepack enable

      - name: Use corepack
        run: corepack use pnpm@latest

      - name: Use Node.js
        uses: actions/setup-node@v6
        with:
          node-version-file: '.nvmrc'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Validate TypeScript
        run: pnpm type-check

      - name: Setup environment
        run: cp .env.example .env

      - name: Get the latest track from Last.fm
        timeout-minutes: 5
        env:
          LASTFM_API_KEY: ${{ secrets.LASTFM_API_KEY }}
          LASTFM_USERNAME: ${{ secrets.LASTFM_USERNAME }}
        run: pnpm get-latest-track

      - name: Replace the README.md with the latest track
        run: cp README.template.md README.md

      - name: Commit and push the updated README.md
        uses: EndBug/add-and-commit@v10
        with:
          add: 'README.md'
          commit: --no-gpg-sign --no-verify --signoff

      - name: Health check
        run: curl -fsS -m 10 --retry 5 -o /dev/null ${{ secrets.HEALTH_CHECK_ENDPOINT }}
