# This workflow runs automatically and updates the README.md file with the
# latest track on Spotify.
#
name: Update Track

on: ["push"]

jobs:
  bump-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_PAT }}
          ref: 'main'
      - name: Use Node.js v16 (LTS)
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'yarn'
      - name: Install dependencies
        run: |
          yarn --frozen-lockfile
      - name: Setup environment
        env:
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          SPOTIFY_USERNAME: ${{ secrets.SPOTIFY_USERNAME }}
          SPOTIFY_PASSWORD: ${{ secrets.SPOTIFY_PASSWORD }}
        run: |
          cp .env.example .env
      - name: Loging into Spotify and get the latest track
        run: |
          yarn get-latest-track
      - name: Replace the README.md with the latest track
        run: |
          cp README.template.md README.md
      - name: Commit and push the updated README.md
        run: |
          git config --local user.name "${{ secrets.GIT_AUTHOR_NAME }}"
          git config --local user.email "${{ secrets.GIT_AUTHOR_EMAIL }}"
          git add README.md
          git commit -m "Updated on $(printf '%(%Y-%m-%d)T' -1)" --no-gpg-sign --no-verify --signoff
          git push
